name: C/C++ CI

on:
  workflow_dispatch:

  push:
    branches: [ "Emulator" ]
  pull_request:
    branches: [ "Emulator" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: cd
      run: cd ./Emulator
    - name: make
      run: make

